### ISSUE TITLE
Homewizard Heatlink support

### ISSUE THREAD

**Issue by sabiwa** [rthewhite/homebridge-homewizard#18]
Thanks for the great application I am using it with a lot of pleasure.

Would it be possible to implement support for the Heatlink also ?

**Comment by rthewhite** [comment]
That's great to hear :+1: 

Yeah should be possible, the heatlink has an api to control the temperature. Unfortunately i don't have an heatlink, but i can try to implement it and then you could test it for me?

**Comment by ygageot** [comment]
Sorry no Heatlink at home to test.

**Comment by sabiwa** [comment]
I van test it for you

**Comment by ygageot** [comment]
sabiwa: why not ! 
If you already configure the Heatlink inside HW,
send me the section heatlink of the result of these 2 HTTP queries : 
http://IP/PASSWORD/get-sensors   and 
http://IP/PASSWORD/get-status
with the IP address of your Homewizard and its PASSWORD

If you don't known the IP address of your HW, execute : http://gateway.homewizard.nl/discovery.php

I am not sure to succeed; It depends if we can configure it inside HomeKit like a thermostat where you know the temperature and you can change the target temperature.

**Comment by ygageot** [comment]
Hello sabiwa: 

Why not ! 
If you already configure the Heatlink inside HW,
send me the section heatlink of the result of these 2 HTTP queries : 
http://IP/PASSWORD/get-sensors 
http://IP/PASSWORD/get-status
with the IP address of your Homewizard and its PASSWORD

If you don't known the IP address of your HW, execute : http://gateway.homewizard.nl/discovery.php <http://gateway.homewizard.nl/discovery.php>
I am not sure to succeed; It depends if we can configure it inside HomeKit like a thermostat where you know the temperature and you can change the target temperature.

**Comment by sabiwa** [comment]
get-sensors:
`{"status": "ok", "version": "3.35", "request": {"route": "/get-sensors" }, "response": {"preset":0,"time":"2016-03-05 16:01","switches":[{"id":0,"name":"Buitenlamp","type":"switch","status":"off","favorite":"no"},{"id":1,"name":"Screen2","type":"asun","mode":1,"favorite":"no"},{"id":2,"name":"Vitrine","type":"switch","status":"off","favorite":"no"},{"id":3,"name":"Koffie","type":"hue","status":"on","hue_id":0,"light_id":5,"color":{"hue":38,"sat":97,"bri":54},"favorite":"no"},{"id":4,"name":"Keuken","type":"hue","status":"on","hue_id":0,"light_id":4,"color":{"hue":47,"sat":98,"bri":57},"favorite":"no"},{"id":5,"name":"Screen1","type":"asun","mode":1,"favorite":"no"},{"id":7,"name":"Eettafel","type":"hue","status":"off","hue_id":0,"light_id":3,"color":{"hue":59,"sat":76,"bri":33},"favorite":"no"},{"id":8,"name":"DVD","type":"hue","status":"off","hue_id":0,"light_id":1,"color":{"hue":61,"sat":72,"bri":78},"favorite":"no"},{"id":9,"name":"Bank","type":"hue","status":"off","hue_id":0,"light_id":2,"color":{"hue":55,"sat":76,"bri":53},"favorite":"no"},{"id":10,"name":"Kerst","type":"dimmer","status":"off","dimlevel":0,"favorite":"no"}],"uvmeters":[],"windmeters":[{"id":2,"name":"Wind thuis","model":0,"unit":0,"favorite":"no"}],"rainmeters":[{"id":3,"name":"Regen thuis","model":0,"favorite":"no"}],"thermometers":[{"id":0,"name":"Buiten","channel":5,"model":0,"te":6.8,"hu":87,"te+":7.7,"te+t":"13:07","te-":-2.5,"te-t":"07:21","hu+":97,"hu+t":"00:00","hu-":87,"hu-t":"13:58","outside":"yes","favorite":"no"},{"id":1,"name":"Binnen","channel":4,"model":0,"te":19.2,"hu":42,"te+":20.1,"te+t":"00:01","te-":17.9,"te-t":"08:37","hu+":45,"hu+t":"00:01","hu-":40,"hu-t":"06:43","outside":"no","favorite":"no"}],"weatherdisplays":[], "energymeters": [], "energylinks": [{"id":0,"favorite":"no","name":"EnergyLink","code":"496839","t1":"solar","c1":2000,"t2":"none","c2":0,"tariff":1,"s1":{"po":189,"dayTotal":5.06,"po+":1570,"po+t":"12:49","po-":0,"po-t":"00:01"},"s2":null,"aggregate":{"po":410,"dayTotal":2.63,"po+":3600,"po+t":"15:24","po-":-1140,"po-t":"12:09"},"used":{"po":600,"dayTotal":7.65,"po+":4033,"po+t":"15:24","po-":130,"po-t":"13:23"},"gas":{"lastHour":0.04,"dayTotal":2.66},"kwhindex":2.53,"wp":2000}], "heatlinks": [{"id": 0, "favorite": "no", "name": "HeatLink", "code": "521325", "pump": "off", "heating": "off", "dhw": "off", "rte": 19.097, "rsp": 19.000, "tte": 0.000, "ttm": null, "wp": 0.000, "wte": 21.597, "ofc": 0, "odc": 0, "presets": [{ "id": 0, "te": 20.00},{ "id": 1, "te": 17.00},{ "id": 2, "te": 20.500},{ "id": 3, "te": 15.00}]}], "hues": [{"id":0,"name":"Hue Bridge","username":"K7g9yKKllzHd8kz","ip":"192.168.10.70"}], "scenes": [{"id": 0, "name": "Alle lampen", "favorite": "no"},{"id": 1, "name": "Woonkamer", "favorite": "no"},{"id": 2, "name": "Screens", "favorite": "no"},{"id": 3, "name": "Buiten", "favorite": "no"},{"id": 4, "name": "Keuken", "favorite": "no"}], "kakusensors": [{"id":0,"name":"Rookmelders","status":null,"type":"smoke","favorite":"no","timestamp":"11:13","cameraid":null},{"id":1,"name":"Voordeur","status":null,"type":"doorbell","favorite":"no","timestamp":"10:57","cameraid":0}], "cameras": [{"id":0,"model":0,"name":"Keuken","username":"homewizzard","password":"smvelpap","ip":"192.168.10.125","port":"80","mode":1,"url":{"path":"snapshot.cgi","query":"user=homewizzard&pwd=smvelpap","auth":""},"presets":[{"id":0,"name":"Deur"},{"id":1,"name":"Kamer"},{"id":2,"name":"Deur2"},{"id":3,"name":"Keukenraam"}]},{"id":1,"model":0,"name":"Keuken2","username":"homewizzard","password":"smvelpap","ip":"Spotweb.veldhuis.nu","port":"1080","mode":1,"url":{"path":"snapshot.cgi","query":"user=homewizzard&pwd=smvelpap","auth":""},"presets":[]}]}}`

get-status
`{"status": "ok", "version": "3.35", "request": {"route": "/get-status" }, "response": {"preset":0,"time":"2016-03-05 16:03","switches":[{"id":0,"type":"switch","status":"off"},{"id":2,"type":"switch","status":"off"},{"id":3,"type":"hue","status":"on","color":{"hue":38,"sat":97,"bri":54}},{"id":4,"type":"hue","status":"on","color":{"hue":47,"sat":98,"bri":57}},{"id":7,"type":"hue","status":"off","color":{"hue":59,"sat":76,"bri":33}},{"id":8,"type":"hue","status":"off","color":{"hue":61,"sat":72,"bri":78}},{"id":9,"type":"hue","status":"off","color":{"hue":55,"sat":76,"bri":53}},{"id":10,"type":"dimmer","status":"off","dimlevel":0}],"uvmeters":[],"windmeters":[{"id":2,"unit":0,"favorite":"no"}],"rainmeters":[{"id":3,"favorite":"no"}],"thermometers":[{"id":0,"te":6.7,"hu":88,"favorite":"no"},{"id":1,"te":19.2,"hu":42,"favorite":"no"}],"weatherdisplays":[], "energymeters": [], "energylinks": [{"id":0,"tariff":1,"s1":{"po":187,"dayTotal":5.06,"po+":1570,"po+t":"12:49","po-":0,"po-t":"00:01"},"s2":null,"aggregate":{"po":340,"dayTotal":2.64,"po+":3600,"po+t":"15:24","po-":-1140,"po-t":"12:09"},"used":{"po":527,"dayTotal":7.67,"po+":4033,"po+t":"15:24","po-":130,"po-t":"13:23"},"gas":{"lastHour":0.04,"dayTotal":2.66},"kwhindex":2.53}], "heatlinks": [{"id": 0, "pump": "off", "heating": "off", "dhw": "off", "rte": 19.097, "rsp": 19.000, "tte": 0.000, "ttm": null, "wp": 0.000, "wte": 21.597, "ofc": 0, "odc": 0}], "kakusensors": [{"id":0,"status":null,"timestamp":"11:13"},{"id":1,"status":null,"timestamp":"10:57"}]}}

`

**Comment by ygageot** [comment]
Fine !
I tried to understand the values.
The target temperature seems to depend only of the preset.
Have you an idea of where is the current temperature ?
is it "WTE" ?

        "rte": 19.097,
        "rsp": 19.000,
        "wte": 21.597,

**Comment by sabiwa** [comment]
wte is the temperature of the water in the boiler
rsp is the target temperature
rte is the real temperature 

If I check the values in the Homewizard app

**Comment by ygageot** [comment]
One thing I don't understand 
rsp=19
but for preset 0 , te= 20

**Comment by sabiwa** [comment]
Rsp is the setting which is setup based on the thermostat itself. Which also has its own program. When you set the temperature throug home wizard it uses the settings till the next program starts

**Comment by sabiwa** [comment]
Sorry my fault. RSP can be set trough two ways.

1. though the clock from the thermostat based on its own program
2. trough the homewizard app and then the setting is until the start of the next program. There is in the app also an option to override it for the next couple of hours

**Comment by ygageot** [comment]
I just pulled a first version to check

**Comment by rthewhite** [comment]
Thanks for picking this up @ygageot :+1: 

Released version 0.0.37 with initial support for the heatlink, so you can test @sabiwa :)

**Comment by sabiwa** [comment]
Is there a way to show which version I am using ? Maybe add it in the output when the plugin starts ?

This is what I see when starting it after updating the build:
Loaded plugin: homebridge-homewizard
Registering platform 'homebridge-homewizard.HomeWizard'
---
Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
Initializing HomeWizard platform...
Loading 0 accessories...
Successfully retrieved accessories from HomeWizard
Skipping: Screen2 because its filtered in the config
Skipping: Koffie because its filtered in the config
Skipping: Keuken because its filtered in the config
Skipping: Screen1 because its filtered in the config
Skipping: Eettafel because its filtered in the config
Skipping: DVD because its filtered in the config
Skipping: Bank because its filtered in the config
Skipping: Kerst because its filtered in the config
Initializing platform accessory 'Buitenlamp'...
Initializing platform accessory 'Vitrine'...
Initializing platform accessory 'Buiten'...
Initializing platform accessory 'Binnen'...
Initializing platform accessory 'Rookmelders'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

**Comment by sabiwa** [comment]
ok seems the update was not working for me in my new pi but after forcing to install version 0.37 it worked.

This is the output I am getting:

Retrieved current heating state for:HeatLink its:on
Retrieved current temperature for:HeatLink its:18.929 degrees
Retrieved target temperature for:HeatLink its:19 degrees

So the communication is working.

**Comment by ygageot** [comment]
I think it is not the last one 
You must see Initializing platform accessory 'HeatLink'... in the log
execute
npm view homebridge-homewizard version
it must be 0.0.37

**Comment by sabiwa** [comment]
after I used eve to turn up the target temperature it moved it up on the heatlink also

Retrieved current heating state for:HeatLink its:on
Retrieved current temperature for:HeatLink its:18.906 degrees
Retrieved target temperature for:HeatLink its:20 degrees

**Comment by ygageot** [comment]
OK
Did you tried to change the target temperature ?
It must change it for 1 hour.

What do you prefer ?
- to change it definitely 
- to change for a fix duration
- to change it for a duration you defined in the config file ?

**Comment by sabiwa** [comment]
Yes I tried to change the temperature and it changed for 1 hour.
I would suggest to leave it to definitely and let the thermostats own program take over. But thats just my opinion. Maybe make it a setting where you can set an time duration or when set to 0 it is definitely ?

**Comment by sabiwa** [comment]
Is it also possible to show the realtime temperature as a thermometer ?

**Comment by ygageot** [comment]
For the duration I propose to have a default of 60 minutes.
If you add some parameter in the config file you can change it to NNN minutes or 0 pour infinite duration
OK ?

**Comment by sabiwa** [comment]
Excellent sollution

**Comment by ygageot** [comment]
For the realtime temperature it is then necessary to create 2 accessories : one Thermostat + one Thermometer.
Why do you prefer that ?

**Comment by sabiwa** [comment]
Right now you don't see the realtime temperature anywhere in homekit apps like eve, but we have the information. So why not use it ?

**Comment by ygageot** [comment]
The temperature is already inside the accessory and an be shown by the UI of the app.
I don't know EVE and its UI.
I use Insteon+ and MyTouchHome
By exemple Insteon+ 
![img_4065](https://cloud.githubusercontent.com/assets/3415324/13554546/ea4605d6-e3aa-11e5-911d-dc69e57c0f91.jpg)
The HomeKit accessory is the same

**Comment by sabiwa** [comment]
Ok then it is an Eve issue not showing the realtime temperature then:
![2016-03-06 14 57 57](https://cloud.githubusercontent.com/assets/774104/13554582/06c424b2-e3ac-11e5-8bad-9a6dff4d2368.png)

**Comment by ygageot** [comment]
Its a large problem because the level of the HomeKit apps are not the same !!
We hope an official app from Apple !!

**Comment by sabiwa** [comment]
I will check what Insteon+ does with Heatsink. Maybe its different then radiotor

**Comment by ygageot** [comment]
The Exe UI must be tested for this elgato equipment
![eve-thermo-solutionshot-icons-en](https://cloud.githubusercontent.com/assets/3415324/13554630/57612dba-e3ad-11e5-857d-757caa847944.png)

**Comment by sabiwa** [comment]
This is what Insteon+ shows

![img_0675](https://cloud.githubusercontent.com/assets/774104/13554660/06bcf460-e3ae-11e5-8e98-f2d0bfb9109e.jpg)

**Comment by rthewhite** [comment]
What's the status on this, is everything working correctly? Can we close the issue?

**Comment by ygageot** [comment]
NO wait the tests

**Comment by sabiwa** [comment]
I will test it more in detail, but for now it looks like it works as a charm

**Comment by sabiwa** [comment]
it looks like the heatlink doesn't use the setting in the config.json.

No matter what I use the time for the setting is always 60 mins

Tried:
      "debug": false,
      "heatlinks" : 0
   }]

and
      "debug": false,
      "heatlinks" : 120
   }]

**Comment by ygageot** [comment]
I corrected the case 0 and added a trace into log with the requested url. I just pulled it.

**Comment by rthewhite** [comment]
Released in 0.0.40 :+1:

**Comment by sabiwa** [comment]
I notice that it still sets the temperature for 60 mins no matter what the setting is. I have debug on true now, where can I find the debug log ?

**Comment by ygageot** [comment]
Have you the last version ?
Try npm view homebridge-homewizard version
it must be 0.0.40

For the log, it is the general log like 
_Loading 1 platforms...
Initializing HomeWizard platform...
...
Initializing platform accessory 'Rookmelders'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
..._
You must read for a target of 21° and infinite duration
hl/0/settarget/21
You must read for a target of 21° and 1 hour (default)
hl/0/settarget/21/60
You must read for a target of 21° and 2 hours
hl/0/settarget/21/120

**Comment by sabiwa** [comment]
yes I have the latest version of the plugin:

pi@raspberrypi:~ $ sudo npm view homebridge-homewizard version
0.0.40

**Comment by sabiwa** [comment]
Can you direct me where the general log is written ?

**Comment by sabiwa** [comment]
Homebridge is running on port 51826.
set target temperature for:HeatLink to:19.0

Thats all I see on screen output

**Comment by ygageot** [comment]
I don't understand 

You must have a  line before "set target...."
With "HW requested  with url:hl /0/settarget/19.0/....."
Yves

**Comment by ygageot** [comment]
@sabiwa I just pushed a version with a display of the running version when the plugin starts.

**Comment by sabiwa** [comment]
I noticed a difference between the following commands to upgrade:

sudo npm upgrade homebridge-homewizard

and 

sudo npm install homebridge-homewizard

With both it shows the right version, but only the latter command makes the extra logging and makes sure the plugin works with the heatlinks setting in the config.

So from now on to update the plugin I will use 
sudo npm install homebridge-homewizard

**Comment by ygageot** [comment]
To by sure of the running version I just pulled an upgrade with a display
When these version will be online, it will be easier !

**Comment by rthewhite** [comment]
Just released 0.0.41 :+1:

**Comment by ygageot** [comment]
@sabiwa you must read
 **Running : homebridge-homewizard 0.0.41**

**Comment by sabiwa** [comment]
As you can see it works. But only when I upgrade by reinstalling.

![image](https://cloud.githubusercontent.com/assets/774104/13668836/971a348c-e6bf-11e5-9f18-dcaaea10b0c6.png)

I also noticed this warning. Don't know if it is serious
![image](https://cloud.githubusercontent.com/assets/774104/13668869/db14127a-e6bf-11e5-9736-128f9cb4c4f5.png)

**Comment by sabiwa** [comment]
I tested the following scenarios

heatlinks 0, heatlinks 90 and heatlinks 15 and every combination works like it should be.

I have the feeling that the enhanchement is fixed. Thanks

**Comment by rthewhite** [comment]
Looks like everything is working, thanks for the implementation ygageot and sabiwa thanks for testing it! :+1: If there are anymore issue, reopen the issue or create a new one.
