### ISSUE TITLE
Config.json to add specific switches from homewizard

### ISSUE THREAD

**Issue by sabiwa** [rthewhite/homebridge-homewizard#2]
Hello Raymond,

I am a bit struggling to add specific switches and not all of them.

When I  use 
    "accessories": [
    ],

The homebridge-homewizard plugin works perfectly, but when I try to add only the switch Vitrinekast and not the rest of it it fails.

Is it possible to do that within the config.json like this ?

    "accessories": [
        {
            "accessory": "HomeWizardSwitch",
            "name": "Vitrinekast"
        }
    ],

**Comment by sabiwa** [comment]
With that configuration I get the following output:

---
Loading 1 platforms...
Initializing HomeWizard platform...
Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:47
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'HomeWizardSwitch' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:47:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:155:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:36:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3

**Comment by rthewhite** [comment]
It's not possible, the accessories array has nothing todo with the HomeWizard plugin. It's an array meant for accessories that are directly supported by Homebridge. 

If you really would want to add specific switches from the HomeWizard i would have to build in some sort of filter functionality.

**Comment by sabiwa** [comment]
If you could do that it would be perfect. Right now when I tell Siri to turn of all lights it lowers the screens also which are in homeward :)

**Comment by rthewhite** [comment]
I will put it on my agenda, need to fix another bug for someone as well. Maybe i will get to it tonight, will let you know when i release a new version.

For now what you could do to achieve what you want, is put the switches you want (light switches) in a scene in Homekit and tell Siri to turn off or on that scene. I use the app Eve to manage the Homekit accessories, there you can create scenes and assign accessories to that scene.

**Comment by rthewhite** [comment]
There is a new version which add an option to the config file filtered.
Put the names of the switches you wanna filter out in there and they will be ignored :+1: 

You can install new version with: sudo npm update -g homebridge-homewizard

**Comment by sabiwa** [comment]
Wow quick support but I am sorry I get an error:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Loaded plugin: homebridge-homewizard
Registering platform 'homebridge-homewizard.HomeWizard'
---
There was a problem reading your config.json file.
Please try pasting your config.json file here to validate it: http://jsonlint.com

/usr/local/lib/node_modules/homebridge/lib/server.js:124
    throw err;
    ^

SyntaxError: Unexpected string
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:118:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:25:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3


With this config.json

{
  "bridge": {
      "name": "Homebridge - DEV",
      "username": "CC:22:3D:E3:CE:40",
      "port": 51826,
      "pin": "031-45-156"
  },
  "description": "Example configuration for Homebridge using the HomeWizard platform.",

    "accessories": [],


  "platforms": [{
      "platform": "HomeWizard",
      "url": "http://192.168.xx.xxx",
      "password": "xxxxxx"
      "filtered": ["Screen 1e"],
      "debug": false
   }]
}

**Comment by rthewhite** [comment]
You missed a comma after password:

```
"platforms": [{
"platform": "HomeWizard",
"url": "http://192.168.xx.xxx",
"password": "xxxxxx",
"filtered": ["Screen 1e"],
"debug": false
}]
}
```

**Comment by sabiwa** [comment]
you are right.

Next step it seems not to filter on my side. How can I check the update ran in a good way ?

Initializing platform accessory 'Buitenlamp'...
Initializing platform accessory 'Screen2'...
Initializing platform accessory 'Vitrinekast'...
Initializing platform accessory 'Koffie'...
Initializing platform accessory 'Keuken'...
Initializing platform accessory 'Screen 1e'...
Initializing platform accessory 'Eettafel'...
Initializing platform accessory 'DVD Kast'...
Initializing platform accessory 'Bank'...
Initializing platform accessory 'Buiten'...
Initializing platform accessory 'Binnen'...

And with infusion+ I still see the Screen 1e in my switches

**Comment by rthewhite** [comment]
Might be related to whitespace, HomeWizard doesn't strip whitespace from the names....

Released a new version which should be more robust related to whitespace. 
When you run the update command afterwards it will log the version it installed.

When you run it now it should be: 0.0.20

**Comment by sabiwa** [comment]
I removed the whitespace for now and restarted the homebridge on server side and still see the screens

I also made sure I had version 0.0.20

config:
  "platforms": [{
      "platform": "HomeWizard",
      "url": "http://xxx.xxx.xx.xxx",
      "password": "xxxxx",
      "filtered": ["Screen1","Screen2"],
      "debug": true
   }]



Output:
":"snapshot.cgi","query":"user=homewizzard&pwd=smvelpap","auth":""},"presets":[]}]}
Initializing platform accessory 'Buitenlamp'...
Initializing platform accessory 'Screen2'...
Initializing platform accessory 'Vitrinekast'...
Initializing platform accessory 'Koffie'...
Initializing platform accessory 'Keuken'...
Initializing platform accessory 'Screen1'...
Initializing platform accessory 'Eettafel'...
Initializing platform accessory 'DVD Kast'...
Initializing platform accessory 'Bank'...
Initializing platform accessory 'Buiten'...
Initializing platform accessory 'Binnen'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

**Comment by rthewhite** [comment]
That's interesting, for me its working. Most off the code is unit tested, and that test also verifies it works.
No clue what the issue would be then, i'll have another look then....

**Comment by sabiwa** [comment]
I am running on Ubuntu with debug now on true but I need to find the logfile so I can help you out with finding the issue. For now I tried it also with "Bank" and "bank" to see if it was just the one switch or not. But no luck at all.

**Comment by rthewhite** [comment]
Well if it does filter, when you start homebridge it should tell you that it skipped an accessory because it was filtered. I just don't get why it's not doing that, while it is working for me. I don't have any time to look into it tonight, but will look into it as soon as i have time :+1:

**Comment by rthewhite** [comment]
Have been looking into this and it all works correctly for me. Like said before there are also unit tests for this and these are all successful as well.

 Try a clean install of homebridge and the plugin and see if this solves it. Gonna close the issue for now.

**Comment by sabiwa** [comment]
Even after a clean instap I have no luck with this one:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-homewizard' since we already loaded the same plugin from '/usr/lib/node_modules/homebridge-homewizard'.
Loaded plugin: homebridge-homewizard
Registering platform 'homebridge-homewizard.HomeWizard'

Initializing platform accessory 'Buitenlamp'...
Initializing platform accessory 'Screen2'...
Initializing platform accessory 'Vitrinekast'...
Initializing platform accessory 'Koffie'...
Initializing platform accessory 'Keuken'...
Initializing platform accessory 'Screen1'...
Initializing platform accessory 'Eettafel'...
Initializing platform accessory 'DVD Kast'...
Initializing platform accessory 'Bank'...
Initializing platform accessory 'Kerst'...
Initializing platform accessory 'Buiten'...
Initializing platform accessory 'Binnen'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

Any suggestions to test it further on my side to see what is wrong here. I am pretty sure its my fault

**Comment by rthewhite** [comment]
Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-homewizard' since we already loaded the same plugin from '/usr/lib/node_modules/homebridge-homewizard'.

This line is interesting, looks like the plugin is installed twice in your machine. Maybe its loading an older version because of this?

**Comment by sabiwa** [comment]
I did clean installed the homebridge-homewizard with npm uninstall -g homebridge-homewizard I can try to do that once more to see if it helps ?

**Comment by rthewhite** [comment]
/usr/local/lib/node_modules/homebridge-homewizard
/usr/lib/node_modules/homebridge-homewizard

Try deleting both these folders by hand and then reinstall using:

npm install homebridge-homewizard@0.0.21 -g

That should then install the latest version again in the right place.

**Comment by sabiwa** [comment]
Perfect that did the trick. I checked the older version and that was version 0.15. thanks you may now close this one

**Comment by rthewhite** [comment]
Cool already suspected that it had to be something like that :+1:  enjoy the plugin :-)
