### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by ygageot** [rthewhite/homebridge-homewizard#27]
I am looking for a virtual accessory where you can query and change the preset with four states At home, Out, Night and Vacancy.
It can be interesting to interface it with HomeKit standard scenes like "Good night",... .

I tried to use **StatefulProgrammableSwitch** with 4 states, without success for the moment with the apps I used.

Have you some ideas of apps supporting this service ?

**Comment by rthewhite** [comment]
Might be an idea to have a look at other plugins for Homebridge, like Domoticz to see if they support functionality like this.

**Comment by ygageot** [comment]
I Will look.
I am interested by several features  
- synchro HW -> HK
- support of Wind&rain (custom services/characteristics ??)
- mapping scenes 
- presets management HW with HK scenes

**Comment by msetten** [comment]
I have built a accessory for the Homewizard Preset, but directly as a .js file as I don't have any experience with the languages used in this project (nor the time to dive into it). I mapped the preset to a security system which actually has four settings which largely overlap. Though the vacation setting does not exist in the security system for homekit, which has been mapped to off. 

Here is the content of the preset.js file I created as a .txt file. Maybe someone can built it properly into this project.

[preset.js.txt](https://github.com/rthewhite/homebridge-homewizard/files/185553/preset.js.txt)

**Comment by rthewhite** [comment]
Thank you for your help @msetten, been actually working on this myself as well. Will have a look tonight to finish it up and release it :+1:

**Comment by ygageot** [comment]
@msetten Thanks for your help.
It is a good idea to use the HomeKit service SecuritySystem.

We will try 
to use SIRI to change the the preset,
to link HomeKit standard scenes like 'good night',...,
to test geolocation

if @rthewhite has not enough time, I will implement it quickly.

**Comment by rthewhite** [comment]
Just released 0.0.47 which has support for presets. It will create a switch for each preset, you can customize the names and turn off the functionality if you want. See the example config.

You can't turn off a preset (HomeWizard doesn't support it, you can only switch between them), so when you tell Siri to turn it off, it will do so but it won't have any effect.

When you set one preset it should update the status off the other presets in Homekit to off, i added event support between accessories for this. A mechanisme we could also use to push status changes for sensors when we start polling for changes. Tested it with Eve, UI in Eve doesn't always seem to update, didn't have time to very that the value actually get's updated in Homekit.
