### ISSUE TITLE
Contact sensor not working

### ISSUE THREAD

**Issue by sissing** [rthewhite/homebridge-homewizard#28]
Hi,

The window contact sensor says in the HomeKit  always Contact Detected. But in the home wizard app I can see the open and close state of this contact sensors correctly.

Thanks,
Ruben

**Comment by rthewhite** [comment]
Hi,
I don't have a contact sensor to test with. Could you supply me with a response of the HomeWizard api to check the code. What you would need to do is open your browser and open the following url:

http://ipadresofhomewizard/yourpassword/get-status

This should give you a list back of accessories, would like to see the status of a contact sensor when there is contact en when there is no contact.

Thanks in advance!

**Comment by sissing** [comment]
Hi,

Here is the get-status response of my homewizard:

{"status": "ok", "version": "3.35", "request": {"route": "/get-status" }, "response": {"preset":2,"time":"2016-03-13 09:13","switches":[{"id":0,"type":"switch","status":"off"},{"id":1,"type":"switch","status":"off"},{"id":2,"type":"switch","status":"on"}],"uvmeters":[],"windmeters":[],"rainmeters":[],"thermometers":[{"id":0,"te":16.8,"hu":46,"favorite":"no"}],"weatherdisplays":[], "energymeters": [], "energylinks": [], "heatlinks": [], "kakusensors": [{"id":0,"status":"no","timestamp":"19:08"},{"id":1,"status":"no","timestamp":"17:46"},{"id":2,"status":"yes","timestamp":"23:56"},{"id":3,"status":"no","timestamp":"09:31"}]}}

id 1: contact sensor 1 (closed)
id 2: doorbell (not pressed)
id 3: contact sensor 2 (open)
id 4: contact sensor 3 (closed)

**Comment by rthewhite** [comment]
Thank you for the information, find the issue. Just released version 0.0.43 with a fix, please update and test :+1:

**Comment by sissing** [comment]
Thanks for the fast update. I only still see that the contact says: contact detected. How can I check the current version of the homewizard plugin on my raspberry pi?

**Comment by rthewhite** [comment]
When you start homebridge is should log the version of the plugin.

**Comment by pacaja** [comment]
How can I get the status of my contact sensor (Klik aan Klik uit). I have installed Insteon+

**Comment by sissing** [comment]
@rthewhite My plugin update failed. The command in the readme documentation has a uppercase letter in Homebridge so the command doesn't work. Now it's working correctly, thanks!

@pacaja Insteon+ doesn't support the contact sensor status, I use iDevices: https://appsto.re/nl/gkiSO.i

**Comment by rthewhite** [comment]
@sissing sorry for the inconvience. Updated the readme right away :+1: Glad that everything is working for you now.

**Comment by pacaja** [comment]
@sissing Thanx!
