### ISSUE TITLE
cannot find homewizard.js

### ISSUE THREAD

**Issue by johnvanl** [rthewhite/homebridge-homewizard#3]
Hi

I am happy with your idea and busy installing it on a raspberryPi.
Installation seems to be successful. But after starting homebridge I get:
Loading 2 platforms...
module.js:338
    throw err;
          ^
Error: Cannot find module './platforms/HomeWizard.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadPlatforms (/home/pi/homebridge/app.js:70:30)
    at startup (/home/pi/homebridge/app.js:27:27)
    at Object.<anonymous> (/home/pi/homebridge/app.js:187:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

npm ERR! Linux 4.1.7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! homebridge@0.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the homebridge@0.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the homebridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls homebridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/npm-debug.log
_____

And yes it's correct that in the home/pi/homebridge/platforms there is no homewizard.js; although I have others there like: Domoticz.js, SmartThings.js and Wink.js. 

I do not see what went wrong during installation or is there another way to install then (sudo) npm install -g homebridge-homewizard?

Thanks an advance! John

**Comment by rthewhite** [comment]
Hi John,

Haven't seen this error before. The only correct way to install is indeed:

```
(sudo) npm install -g homebridge-homewizard
```

How does you config file look?

**Comment by johnvanl** [comment]
I will do a clean install.
My config is:
{
  "bridge": {
      "name": "Homebridge",
      "username": "CC:22:3D:E3:CE:33",
      "port": 51826,
      "pin": "031-45-155"
  },
  "description": "Example configuration for Homebridge using the HomeWizard platform.",
  "accessories": [
  ],
  "platforms": [
    {
      "platform": "HomeWizard",
      "url": "http://192.168.178.252",
      "password": "xxxxxxx",
      "filtered": ["deviceName"],
      "debug": false
    }
  ]
}

(the only thing changed in this config is the password)

**Comment by rthewhite** [comment]
Ok that config should be fine. Should be a problem with the installation then probably indeed.
Let me know what the result is of your clean install.

**Comment by johnvanl** [comment]
Clean (manual and according to your instructions) install solved my problem. Sorry for bothering!

**Comment by rthewhite** [comment]
No problem John, happy it works for you :+1:
