### ISSUE TITLE
Somfy Sunscreen

### ISSUE THREAD

**Issue by pacaja** [rthewhite/homebridge-homewizard#30]
I have a Somfy sunscreen connected to my Homewizard. I have installed Insteon+ too configure some things. Whatever i try i cannot let SIRI open my sunscreen. Should this work? if yes, what am i doing wrong?

**Comment by rthewhite** [comment]
I believe it should work, don't have Somfy sunscreens myself. @ygageot implemented this feature maybe he can help you out?

**Comment by Nnk2** [comment]
Same issue here: I can see my Somfy blinds & curtains OK in Insteon+ (and they work OK in the Homewizard app), but they do not have any switches showing ... and Siri does not know what to do with them ... any hint/tips? How can I tell the Homebridge/Homekit that these can actually move?

**Comment by basvdploeg** [comment]
Insteon+ won't let you controll the Symfy blinds and curtains, but you can controll them using Siri. I used the Insteon app to rename the Siri name to something unique, in my case "Somfy rolgordijn". Now I can say things like (in Dutch): 

> **"Open mijn rolgordijn 100%"** – To open them fully
> **"Open mijn rolgordijn helemaal"** – To open them fully
> **"Sluit mijn rolgordijn"** – To close them fully
> **"Open mijn rolgordijn 50%"** – This is your favorite (My) position.

**Comment by pacaja** [comment]
@basvdploeg I have tried the above but nothing. With sunscreen I mean " zonnescherm aan de buitenkant van het huis" but I think the working is the same as you're rolgordijnen.

**Comment by basvdploeg** [comment]
Can you test the sunscreen by using these requests:

    http://ip-homewizard/password/sf/0/down
    http://ip-homewizard/password/sf/0/up
    http://ip-homewizard/password/sf/0/stop

If you have more Somfy blinds you need to change the 0 in the url's to the right maching ID number.

**Comment by pacaja** [comment]
The sunscreen is going down when I use: http://192.168.X.X/password/sw/40/down and up when I use: http://192.168.X.X/password/sw/40/up

**Comment by basvdploeg** [comment]
That means that they work just like the Brel motors in this issue: https://github.com/rthewhite/homebridge-homewizard/issues/22

Do they have a special type, like Brel?

```
         {
            "id":1,
            "name":"Gordijnen",
            "type":"brel",
            "mode":0,
            "favorite":"no"
         },
```
If so, maybe @rthewhite can add them to the plugin as **WindowCovering**.

**Comment by pacaja** [comment]
@basvdploeg 
type:"somfy"

**Comment by basvdploeg** [comment]
Weird, I think that should work already. Have you tried changing the Siri name to something else?

**Comment by pacaja** [comment]
@basvdploeg Yep, strange.

**Comment by rthewhite** [comment]
Ok then that's probably the issue. For type somfy we use the url:

 http://192.168.X.X/password/sf/40/down

Which i think was needed for Somfy shutters, but i didn't implement it but @ygageot did. Not sure on how to fix this if they have both the same type but need different url's....

**Comment by pacaja** [comment]
@rthewhite This is also working: http://192.168.X.X/password/sw/40/down

**Comment by rthewhite** [comment]
Yes i understand, that's actually the problem. Notice the sw/sf difference?
The plugin currently uses the sf url for type somfy. Which was need for the shutters, but apparently doesn't work for your sunscreen.

**Comment by pacaja** [comment]
@rthewhite Now it's clear!!

**Comment by Nnk2** [comment]
Only Siri does not seem to work with these: all other options described seem to work (as does the "Home" app on iOS ... it seems to be a siri/voice recognition issue (only), when linking the Homewizard, through homebridge to my somfy curtains, shutters/blinds ... I can control other switches this wat though: my "keukenlamp" (also only accessible throuh my Homewizard) works fine ...

**Comment by rthewhite** [comment]
Ok laten we de taal barrière ff weghalen. Heb alles nog eens terug gelezen en als ik het goed begrijp gaat het zonnescherm omlaag wanneer je deze url gebruikt:

``` 
 http://192.168.X.X/password/sf/40/down
```

En is het type: 'somfy', correct?
Dat is namelijk wat de plugin nu ook verstuurt als het goed is, als dat zo is dan is het inderdaad vermoedelijk een probleem met de Siri spraak herkenning. Wanneer je het rechtstreeks vanuit een Homekit app zoals Eve of Insteon doet zonder Siri maar gewoon met de slider/knop werkt het dan wel?

**Comment by pacaja** [comment]
Je vraag over de onderstaande url klopt en het is een type somfy. Als ik de Eve app gebruik en ik klik op 1 van de knoppen gebeurt er eigenlijk niets. Als ik veel op de knop ^ klik en daarna weer op de andere knop gaat het zonnescherm uit (down) maar dit is niet echt heel stabiel gedrag (soms wel, soms niet). Ik moet het zonnescherm weer met de Homewizard app in (up) doen.

**Comment by rthewhite** [comment]
Ok dan weet ik vermoedelijk waar het probleem zit. Siri en Homebridge ondersteunen een range 0 tot 100. Echter de HomeWizard doet alleen omhoog, omlaag en stop. Dus wat er gedaan is om dit te implementeren is dat wanneer de waarde 0 is de schermen omlaag gaan, bij 100 omhoog en tussen de 40 en 60 stop. Dit werkt op zich als je een slider heb, echter met knoppen is dit vrij lastig....

**Comment by pacaja** [comment]
Als ik met Eve de positie op 100% zet gebeurt er eigenlijk niets. Ook niet met Home. Ik laat het voor nu maar even rusten. Bedankt in ieder geval.

Groetjes Patrick

**Comment by pacaja** [comment]
Ik gebruik nu plugin homebridge-http
Door nu te zeggen zet zonnescherm aan/uit gaat het scherm uit of in.
 Is er een manier om ook een stop signaal, http://192.168.X.X/password/sw/40/stop te sturen?

	{
	"accessory": "Http",
	"name": "Zonnescherm",
	"switchHandling": "realtime",
	"http_method": "GET",
	"on_url":      "http://192.168.X.X/password/sw/40/down",
	"off_url":     "http://192.168.X.X/password/sw/40/up",
	"status_url":  "",
	"service": "Light",
	"brightnessHandling": "no",
	"brightness_url":     "",
	"brightnesslvl_url":  "",
	"sendimmediately": "",
	"username" : "",
	"password" : ""					    
      }

**Comment by ygageot** [comment]
What I am sure :

With HW curtains : type=brel it works  with SW not SF !
With my  Somfy RTS external shutter type=somfy It works with SF
I never tried  with SW

I propose at the end of the week to modify the plugin with the following behavior :
The first time an acccessoiry is used  we verify the update of effective, if  not,
 we try the other way

**Comment by pacaja** [comment]
@ygageot 

I have Somfy RTS external shutter (type = somfy) that works with:

http://192.168.X.X/password/sf/40/down and
http://192.168.X.X/password/sw/40/down

Should the plugin do the job right now?

**Comment by basvdploeg** [comment]
If both **sf** and **sw** can control the shutters, the plugin should work (since **sf** is just the same as other Somfy window covering). I keep thinking the Siri name is the problem. Have you tried to ask Siri to lower the "rolgordijn” instead of the “zonnescherm”?

**Comment by pacaja** [comment]
@basvdploeg 
I heb de SIRI naam gewijzigd in Rolgorijn. Als ik vraag aan SIRI: Doe het rolgordijn naar beneden is het antwoord: Sorry, ik kan geen apparaten vinden.

**Comment by basvdploeg** [comment]
@pacaja Oké, even om alles uit te sluiten. Mijn instellingen in Insteon+:

Device Name: **Rolgordijn**
Siri Control: **Somfy rolgordijn**

Zeg tegen Siri: **"Sluit mijn rolgordijn" **

**Comment by pacaja** [comment]
@basvdploeg That does the trick!! Strange!

**Comment by basvdploeg** [comment]
Now try to play with the Siri name to make it fin in your situation. :)

**Comment by pacaja** [comment]
@basvdploeg I have tried mutiple SIRI names but only rolgordijn works!

**Comment by ygageot** [comment]
In my case it works well if I say the name of the room like (in french)

Lève le volet du bureau

Baisse tous les volets

**Comment by rthewhite** [comment]
Cool sounds like this issue is solved :+1: Closing the issue, if you experience any issues you can reopen it or create a new one.
