### ISSUE TITLE
Outlet instead of Light category types

### ISSUE THREAD

**Issue by basvdploeg** [rthewhite/homebridge-homewizard#32]
Some of my HomeWizard (KlikAanKlikUit) switches are connected to lights, but others are connected to accessories like fans, speakers, etc.

When I ask Siri to turn of the lights in my home, it shuts off ALL the (KlikAanKlikUit) switches because the plugin sees them all as lights.

Is it possible to add an option in the configuration file (just like the “filtered” option?) where users can specify if the connected switch needs to be used as a “outlet” type, instead of a “light”? That way Siri will not shut them down when asking to turn of all the lights.

**Comment by rthewhite** [comment]
Good one, working on it right now :+1:

**Comment by rthewhite** [comment]
Implemented and released in version 0.0.44.

If the type of the switch isn't: somfy, brel, hue or radiator you can specify the switchType in the config and it will be initialized as such. See the example config in the readme, supported types are: switch, fan, outlet and lightbulb. I left the default type if not specified lightbulb for backwards compatibility.
