### ISSUE TITLE
Asun screen switches

### ISSUE THREAD

**Issue by sabiwa** [rthewhite/homebridge-homewizard#34]
Is it possible to build in support for these asus screens ?

If I look at get-sensors I see them (Screen1 and Screen2) but in get-status they are not visible.
But in the Homewizard app I see an up and down button. Pressing them again the movement stops.

Get-sensors

"switches":[
{"id":0,"name":"Buitenlamp","type":"switch","status":"off","favorite":"no"},

{"id":1,"name":"Screen2",
	"type":"asun",
	"mode":1,
	"favorite":"no"
},

{"id":2,"name":"Vitrine","type":"switch","status":"off","favorite":"no"},
{"id":3,"name":"Koffie","type":"hue","status":"on","hue_id":0,"light_id":5,"color":{"hue":38,"sat":97,"bri":54},"favorite":"no"},
{"id":4,"name":"Keuken","type":"hue","status":"on","hue_id":0,"light_id":4,"color":{"hue":47,"sat":98,"bri":57},"favorite":"no"},
{"id":5,"name":"Screen1","type":"asun","mode":1,"favorite":"no"},
{"id":7,"name":"Eettafel","type":"hue","status":"off","hue_id":0,"light_id":3,"color":{"hue":59,"sat":76,"bri":33},"favorite":"no"},
{"id":8,"name":"DVD","type":"hue","status":"off","hue_id":0,"light_id":1,"color":{"hue":61,"sat":72,"bri":78},"favorite":"no"},
{"id":9,"name":"Bank","type":"hue","status":"off","hue_id":0,"light_id":2,"color":{"hue":55,"sat":76,"bri":53},"favorite":"no"},
{"id":10,"name":"Kerst","type":"dimmer","status":"off","dimlevel":0,"favorite":"no"}]

Get-status

"switches":[
{"id":0,"type":"switch","status":"off"},
{"id":2,"type":"switch","status":"off"},
{"id":3,"type":"hue","status":"on","color":{"hue":38,"sat":97,"bri":54}},
{"id":4,"type":"hue","status":"on","color":{"hue":47,"sat":98,"bri":57}},
{"id":7,"type":"hue","status":"off","color":{"hue":59,"sat":76,"bri":33}},
{"id":8,"type":"hue","status":"off","color":{"hue":61,"sat":72,"bri":78}},
{"id":9,"type":"hue","status":"off","color":{"hue":55,"sat":76,"bri":53}},
{"id":10,"type":"dimmer","status":"off","dimlevel":0}]

**Comment by rthewhite** [comment]
Sure if you can figure out what the api is for them. See that they don't have a status for example, is there away to get there status? And what is their api to open/close them?

**Comment by sabiwa** [comment]
http://ip-homewizard/password/sw/0/down
http://ip-homewizard/password/sw/0/up
http://ip-homewizard/password/sw/0/stop

**Comment by rthewhite** [comment]
Ok, so basically this has to behave the same as the somfy windowcovering. Will try to see if i can make some time this week to implement this :+1:

**Comment by ygageot** [comment]
It is difficult to consider that "type=asun" is only a WindowCovering, it can be switches,....
**Do you know the meaning of MODE  ?**

For my Somfy shutter I have type='somfy', mode=0

In these issue we have type='asun', mode=1

**Comment by sabiwa** [comment]
it is the ASUN-650 I assume there are more ASUN switches but I can't find them

**Comment by ygageot** [comment]
It seems that actually HW supports only ASUN-650 modules (probably DIO/Chacon 54754/51 equivalents).
I will update the software soon, considering the type='asun' is for the moment only for windowing.

**Comment by ygageot** [comment]
It seems that actually HW supports only ASUN-650 modules (probably DIO/Chacon 54754/51 equivalents).
I just pushed an update, considering the type='asun' is for the moment only for windowing.

@sabiwa thanks to test it

**Comment by rthewhite** [comment]
Great, thanks @ygageot didn't find time yet to do this :+1:

**Comment by sabiwa** [comment]
Neither with Siri, nor with Eve or Insteon+ can I find a way to lower or rise the screens. In Eve it gives me a percentage and in Insteon+ the screens are not even recognized as window openers

**Comment by ygageot** [comment]
Insteon+ do not support WindowCovering.
Eve do.

The TargetPosition in HomeKit is a percentage !

With app Eve :
To open push to 100%
To close 0%
To stop in the middle around 50% (40-60)
The other values are ineffective 

There Is no feed-back also HomeKit dont know the CurrentPosition

For Siri I use the room name in place of the acccessoiry name.

"Ouvre les volets du bureau"
"Ferme tous les volets"
(Sorry for the french)

**Comment by sabiwa** [comment]
Ok it works but for the ASUN the % is not used as it doesn't stop but thats not a real issue of the code

**Comment by ygageot** [comment]
@sabiwa : I think that the http STOP has no effect.  can you try the http request with 2 consecutive UP

**Comment by sabiwa** [comment]
@ygageot you are right the stop doesn't work at all. When the screen is going down an extra down stops.  If the screen goes up an extra up stops.

But when the screen goes down and you send an up it goes up straight away without stopping.

**Comment by ygageot** [comment]
@sabiwa In the version 0.0.50 I made an ASUN specific update.
Try to ask SIRI to open or close your device.
And ask during the motion to "open at 50%", it must stop the motion.
In fact any value between 40% and 60% will stop. 
The plugin will redo an up or down to do that !

**Comment by sabiwa** [comment]
Because both my screens are broken at this moment testing have to wait until they are fixed sorry.
