### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by ygageot** [rthewhite/homebridge-homewizard#43]
I just install the plugin and its environnement on a Raspberry Pi2 with Debian 7.9 (wheezy).
It works well.
I am astonished to see that on the PI the log format is prefixed by date+time like 

_[2016-03-30 20:51:27] Retrieved power state for: Vacances, false_

on my Mac 10.11.4  I have only the message without prefix

Is there a conflict between homebridge and the plugin loggers ?

**Comment by rthewhite** [comment]
Think this is platform related, depending on the OS and platform the log format might be different.
When the plugin initialises it get's a log function from Homebridge and that's the one we are using every where. 

I actually made a start by making a logger class, have different log levels and even colored output in the logs but haven't gotten to it to actual update it all over the plugin to start using it.

**Comment by ygageot** [comment]
In fact it was my fault ! 
I was using all the  time an "old" version of Homebridge.
With the current version I have date+time was a prefix in the log on my Mac.
