### ISSUE TITLE
iOS 10 Home app not responding messages

### ISSUE THREAD

**Issue by msetten** [rthewhite/homebridge-homewizard#44]
When using the iOS 10 Home app, all accessories that are connected to the HomeWizard via the Homebridge-homewizard plugin get "not responding messages". Any idea how to solve this.

**Comment by rthewhite** [comment]
My initial guess would be that it's more of a homebridge issue then an issue of the homewizard-plugin. I did some quick testing with iOS10 and my plugin for Domoticz which shares the same architecture and that all seemed to work fine. 

Don't have much time to dive into it right now, when iOS10 is officially out I will update my devices as well and I will try to test it with the domoticz plugin to see if i encounter any issues.

**Comment by msetten** [comment]
A complete reinstall of homebridge did the trick. Sorry for the confusion.
