### ISSUE TITLE
events.js error

### ISSUE THREAD

**Issue by msetten** [rthewhite/homebridge-homewizard#46]
I'm getting these errors, but I can't figure out what is causing them:

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:855:11)
    at TCP.onread (net.js:544:26)

Maybe a silly question, but the weird thing is that if I look at events.js, there isn't a line 141. What am I missing or what is causing this? Any help?

**Comment by rthewhite** [comment]
Sounds like a problem related to the connection to the HomeWizard. Make sure your ip address and password are correct in the config. 

And keep into account there is known issue related to special characters in the password

**Comment by msetten** [comment]
It all did work without any issues, but suddenly it started acting up. I did add two smoke detectors, but even if I now let the plugin ignore them in the config file, it still creates these errors. What I am wondering about is, where can we catch these errors in the plugin, so that it doesn't crash the homebridge and homebridge-homewizard plugin?

**Comment by rthewhite** [comment]
Depends on where the error happens. Calls to the homewizard are being done in api.js, and the accessories are supposed to catch the errors when they occur. Might be that some error isn't catched correctly. 

Does it happen right away when you start homebridge?

**Comment by msetten** [comment]
No, it works for a while and then suddenly this error occurs. I just did a full reset of both my mac mini (where the homebridge runs) and the home wizard and will keep monitoring this issue. Try to figure out if it happens with a specific type of accessory being updated. Will let you know.

**Comment by msetten** [comment]
I keep having this issue popping up every now and then. Again at the same place:

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ETIMEDOUT
    at exports._errnoException (util.js:855:11)
    at TCP.onread (net.js:544:26)

Maybe it happens if the homewizard is too busy to reply in time to a request or it gets too many requests at once (I have seen delays in the homeward app itself too). 

Is there any way to at least somehow gracefully handle this timeout error in events.js so that it doesn't crash the homebridge-homewizard plugin and then homebridge?
