### ISSUE TITLE
Smokedetector

### ISSUE THREAD

**Issue by AlainBijl** [rthewhite/homebridge-homewizard#52]
Hi,

I just recently installed some smoke detectors (Homewizard/Smartwares). When asked at Siri, I can get the status of my Smokedetectors but Siri always says an alarm is triggered. The Home app also displays: Smoke detected.

Here is my get-sensors dump for the Kakusensors:

{"status": "ok", "version": "3.372", "request": {"route": "/get-sensors" }, "response":
{"kakusensors": [
{"id":0,"name":"Deurbel","status":"no","type":"doorbell","favorite":"no","timestamp":"09:30","cameraid":null},
{"id":1,"name":"Rookmelders","status":"yes","type":"smoke","favorite":"no","timestamp":"18:14","cameraid":null}],}}

I tested the smoke detector at 18h14 as you can see, will this reset automatically after a while or is there something other going on?

Best regards,
Alain

**Comment by AlainBijl** [comment]
I see now this is probably related to Issues #5 ?

**Comment by ygageot** [comment]
In a today version , I update that.
Now we consider an alarm during only 10 minutes not indefinitely (using the timestamp)
I do not know if the smoke sensor in real world reemit periodically during the positive detection.

Look at the last version to notify HomeKit immediatly when detection occurs.

**Comment by rthewhite** [comment]
Closing this one, if there are any other issues/questions regarding this please re-open.
