### ISSUE TITLE
Install / update issues

### ISSUE THREAD

**Issue by msetten** [rthewhite/homebridge-homewizard#56]
I just tried to update to the latest version but I am getting errors during install. Even a clean install does not work. 

I used the following command to install: sudo npm install -g homebridge-homewizard
Also tried it with the --unsafe-perm parameter, same errors.

These are the errors when I try a clean install:
`npm ERR! not a package /Users/mark/homebridge-homewizard
npm ERR! addLocal Could not install /Users/mark/homebridge-homewizard
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "--unsafe-perm" "homebridge-homewizard"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! path /tmp/npm-4912-4ad4e4ba/unpack-f66d290bed08965d3cf9c55d801b4d7c/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/tmp/npm-4912-4ad4e4ba/unpack-f66d290bed08965d3cf9c55d801b4d7c/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mark/npm-debug.log`

Also added the npm-debug.log:
[npm-debug.log.txt](https://github.com/rthewhite/homebridge-homewizard/files/730132/npm-debug.log.txt)

Hope someone can help.

**Comment by rthewhite** [comment]
Try running: npm cache clean and then install again see if it works.

**Comment by msetten** [comment]
That didn't fully help. After the clean I still got errors. But I then tried to first go to the homebridge-homewizard folder with the cd command. And then another clean after that install worked.
