### ISSUE TITLE
Heatlink

### ISSUE THREAD

**Issue by joelvanderkuur** [rthewhite/homebridge-homewizard#58]
Hello,

My Heatlink is not responding, updated to 0.57.
Have my homewizard deleted from the HomeKit app and added again, get the Heatlink pop up with adding it . but no response. 

Update:
After 30 minutes there was reaction!
Dont know wat happend

**Comment by ygageot** [comment]
I do not understand because you must find you heatlink as a Thermostat in Apple Home app.
And the Home UI must be refreshed automatically every minute if you change target temperature in HW app or if the current temperature change.
