### ISSUE TITLE
Crash if HomeWizard is unavailable or returns an error

### ISSUE THREAD

**Issue by msetten** [rthewhite/homebridge-homewizard#8]
I noticed that if for some reason the HomeWizard is temporarily unavailable or giving a one time error back (which happens every now and then), the whole homebridge-homewizard plugin make the homebridge crash. I think it is due to the fact that for example for thermometers a null value is returned instead of a legal number if a try fails. Wouldn't if be possible to either return a default value or the last actually retrieved value (if there is a way to keep track of that), so that the whole homebridge doesn't crash?

**Comment by rthewhite** [comment]
Ok haven't experienced that problem yet, or my Homebridge restart automatically then because i'm using forever to run it. Gonna give this plugin some love this weekend and gonna try to implement some features like pushing changes to Homebridge. Will look into this as well!

**Comment by msetten** [comment]
Maybe my wording was not totally accurate. It doesn’t fully crash as the error itself is caught. It prints the error and then returns a null value which makes the homebridge-homewizard plugin no longer available after that. I have to manually stop homebridge using CTRL-C and then start it again. So something like forever won't catch this.

I assume the issue is the final callback(error, null) of:

`getValues(callback) {
    return this.api.request({url: 'get-status'}).then(data => {
      return data.response.thermometers.find(sensor => {
        return sensor.id === this.id;
      });
    }).catch(error => {
      this.log(``Failed to retrieve temperature/humidity for: ${this.name}``);
      this.log(error);
      callback(error, null);
    });
  }`

But I may be mistaken of course.

**Comment by rthewhite** [comment]
Ok, will have to look into the error handling of Homebridge then. Though this was the appropriate way of passing errors to Homebridge but apparently not then. It is only caused by the thermometers?

**Comment by msetten** [comment]
I am not sure it's just the thermometers. If the homewizards is not responding or responding with an error, I only see the error, but not which sensor was causing it. I looked at the code myself and noticed the null value return for the thermometers, causing me to believe that might be the cause. Next time it happens with an error response from the homewizard, I'll copy that error in the thread.

**Comment by rthewhite** [comment]
Ok i made some changes regarding the callbacks, also the performance of the api calls has been improved drastically which minimizes the amount of failing calls. 

I experienced failing calls sometimes as well, especially when you asked Siri to do something for the first time. I think it then retrieved the current state first, which fired a lot of requests to the HW, making some of the calls fail. 

Try the latest release and see if the issue persists, if so re-open the issue please :+1:
